# Generated by Django 3.1.7 on 2021-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todojob',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todojob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todojob',
            name='image',
        ),
        migrations.AlterField(
            model_name='todojob',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todojob',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
