# Generated by Django 3.1.7 on 2021-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210403_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todojob',
            name='image',
            field=models.ImageField(blank=True, default=' static/default.png', null=True, upload_to=''),
        ),
    ]
