# Generated by Django 3.1.7 on 2021-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210413_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todojob',
            name='image',
            field=models.ImageField(blank=True, default='static/icon.png', null=True, upload_to=''),
        ),
    ]
