# Generated by Django 3.1.7 on 2021-04-14 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_auto_20210413_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todojob',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todojob',
            name='image',
            field=models.ImageField(blank=True, default=' static/icon.png', null=True, upload_to=''),
        ),
    ]
