# Generated by Django 3.1.7 on 2021-04-20 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_auto_20210414_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todojob',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Todojobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
