# Generated by Django 3.1.7 on 2021-04-22 13:01

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210421_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='todojob',
            name='image',
        ),
        migrations.AddField(
            model_name='todojob',
            name='image',
            field=models.ManyToManyField(related_name='tasks', to='jobs.Image'),
        ),
    ]
