# Generated by Django 3.1.7 on 2021-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210422_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todojob',
            name='image',
        ),
        migrations.AddField(
            model_name='todojob',
            name='image',
            field=models.ImageField(default='/static/icon.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
